# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{carpodaster-unicase}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bkkgrad", "Carsten Zimmermann"]
  s.date = %q{2010-11-11}
  s.description = %q{Upcase and downcase methods for non-ASCII string; originally taken from bkkbrad/unicase}
  s.email = %q{carp@hacksocke.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/case_data.dat",
     "lib/case_data_creator.rb",
     "lib/unicase.rb",
     "test/unicase_test.rb"
  ]
  s.homepage = %q{http://github.com/carpodaster/unicase}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Unicase-aware upcase and downcase}
  s.test_files = [
    "test/unicase_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

